# Site settings
title: Artur Gomes # site title
description: >- # site description
  My project, blog, news stuff.
lang: en-US # default lang
timezone: America/Sao-paulo # set your timezone
image: assets/img/avatar.jpg # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/arturgoms/arturgoms.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Artur Gomes # author name
  bio: >- # tell to the world
    Back-end python developer currently working at <a href="https://pixelwolf.com.br" target="_blank" rel="noopener">@pixelwolf</a>
    You can find my project here <a href="https://github.com/piharpi/jekyll-klise" target="_blank" rel="noopener">@github</a>.

    And download my resume <a class="footer_item" href="/assets/CV.pdf">here</a>.
  username: arturgomes # general username
  github: arturgoms # github username
  twitter: arturgoms # twitter username=
  email: contato@arturgomes.com.br # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://arturgomes.com.br" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true
  projects:
    output: true


# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:
  project_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limits
number_of_posts: 5
number_of_projects: 3

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
